name: AI Code Review & Test Generation (Demo Repo)

on:
  pull_request:
    types: [opened, synchronize, reopened]

jobs:
  ai_pipeline:
    runs-on: self-hosted

    env:
      ENV: local
      LLM_PROVIDER: ollama
      LLM_MODEL: qwen2.5-coder:1.5b
      OLLAMA_URL: http://localhost:11434
      ENABLE_AI_REVIEW: true
      ENABLE_AI_TEST_GEN: true
      BLOCK_ON_CRITICAL: false
      MAX_AI_COMMENTS: 5

    steps:
      - name: Checkout demo repo
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Checkout pipeline repo
        uses: actions/checkout@v4
        with:
          repository: Misty033/ai-code-review-test-generation-pipeline-v1
          ref: main
          path: pipeline
          token: ${{ secrets.PIPELINE_REPO_TOKEN2 }}
          fetch-depth: 0

      - name: Use Python 3.11
        shell: powershell
        run: |
          $pythonPath="C:\Users\BAPS\AppData\Local\Programs\Python\Python311\python.exe"
          echo "PYTHON_PATH=$pythonPath" >> $env:GITHUB_ENV
          & $pythonPath --version

      - name: Install dependencies
        shell: powershell
        run: |
          & $env:PYTHON_PATH -m venv venv
          .\venv\Scripts\Activate.ps1
          pip install --upgrade pip
          pip install -r pipeline/requirements.txt

      - name: Set PYTHONPATH
        shell: powershell
        run: |
          echo "PYTHONPATH=${{ github.workspace }}/pipeline/src;${{ github.workspace }}" >> $env:GITHUB_ENV

      - name: Set UTF-8 encoding
        shell: powershell
        run: |
          echo "PYTHONUTF8=1" >> $env:GITHUB_ENV
          echo "PYTHONIOENCODING=utf-8" >> $env:GITHUB_ENV

      - name: Run integration test
        shell: powershell
        run: |
          .\venv\Scripts\Activate.ps1
          python pipeline/integration_test.py


      - name: Run full pipeline
        shell: powershell
        env:
          PR_NUMBER: ${{ github.event.pull_request.number }}
          EVENT_TYPE: ${{ github.event.action }}
        run: |
          .\venv\Scripts\Activate.ps1

          python -c "
          import os
          from pipeline.orchestrator import start_pipeline

          pr = int(os.environ['PR_NUMBER'])
          ev = os.environ['EVENT_TYPE']

          result = start_pipeline(pr, ev)

          print('PIPELINE RESULT:')
          print(result)
          "

      - name: Upload AI results
        uses: actions/upload-artifact@v4
        with:
          name: ai-review-results
          path: pipeline/artifacts/
